
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ibrah
 */
public class AddMedicine extends javax.swing.JFrame {
    public String numberPattern = "^[0-9]*$";
    /**
     * Creates new form AddMedicine
     */
    public AddMedicine() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CloseIcon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MedicineIDTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CompanyNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ManufactureDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        ExpirationDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        QuantityTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PriceTxt = new javax.swing.JTextField();
        SaveIcon = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Add Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 10));

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        CloseIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseIconActionPerformed(evt);
            }
        });
        getContentPane().add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 88, -1, -1));

        MedicineIDTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(MedicineIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 116, 300, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 156, -1, -1));

        NameTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 184, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 224, -1, -1));

        CompanyNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(CompanyNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 252, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Manufacture Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 292, -1, -1));
        getContentPane().add(ManufactureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 320, 300, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Expiration Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 88, -1, -1));
        getContentPane().add(ExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 116, 300, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 156, -1, -1));

        QuantityTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(QuantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 184, 300, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Price Per Unit");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 224, -1, -1));

        PriceTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(PriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 252, 300, -1));

        SaveIcon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SaveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        SaveIcon.setText("Save");
        SaveIcon.setActionCommand("");
        SaveIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveIconActionPerformed(evt);
            }
        });
        getContentPane().add(SaveIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 315, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseIconActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseIconActionPerformed
    String url = "jdbc:mysql://localhost:3306/pharmacy_management_system_db";
    String user = "root";
    String dbpassword = "IBRAHIM2525";
    private void SaveIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveIconActionPerformed
        // TODO add your handling code here:
        String medicineID = MedicineIDTxt.getText();
        String medicineName = NameTxt.getText();
        String companyName = CompanyNameTxt.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date manDate = ManufactureDate.getDate();
        String manufactureDate = "";
        if(manDate != null){
            manufactureDate = dFormat.format(ManufactureDate.getDate());
        }
        Date ExpDate = ExpirationDate.getDate();
        String expirationDate = "";
        if(ExpDate != null){
            expirationDate = dFormat.format(ExpirationDate.getDate());
        }
        String quantity = QuantityTxt.getText();
        String price = PriceTxt.getText();
        
        if (medicineID.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Medicine ID field is required");
        } else if (medicineName.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Medicine Name filed is required");
        } else if (companyName.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Company Name field is required");
        } else if (manufactureDate.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Manifacture Date field is required");
        } else if (expirationDate.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Expiration Date field is required");
        } else if (quantity.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Quantity field is required");
        }else if(!quantity.matches(numberPattern)) {
            JOptionPane.showMessageDialog(this, "Quantity field is Invalid");         
        }else if (price.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Price field is required");
        }else if(!price.matches(numberPattern)) {
            JOptionPane.showMessageDialog(this, "Price field is Invalid");         
        }else{
            try{
                Connection con = DriverManager.getConnection(url, user, dbpassword);
                String sql = "INSERT INTO MEDICINE (medicine_id, medicine_name, company, man_date, exp_date, quantity, price)values(?,?,?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, medicineID);
                pst.setString(2, medicineName);
                pst.setString(3, companyName);
                pst.setString(4, manufactureDate);
                pst.setString(5, expirationDate);
                pst.setString(6, quantity);
                pst.setString(7, price);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Medicine Added Successfully");
                setVisible(false);
                new AddMedicine().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_SaveIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseIcon;
    private javax.swing.JTextField CompanyNameTxt;
    private com.toedter.calendar.JDateChooser ExpirationDate;
    private com.toedter.calendar.JDateChooser ManufactureDate;
    private javax.swing.JTextField MedicineIDTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JTextField QuantityTxt;
    private javax.swing.JButton SaveIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
