
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ibrah
 */
public class AdminDashboard extends javax.swing.JFrame {

    private String username = "";

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    public AdminDashboard(String tempUsername) {
        initComponents();
        username = tempUsername;
        System.out.println(username);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AddUserIcon = new javax.swing.JButton();
        ProfileIcon = new javax.swing.JButton();
        ViewUserIcon = new javax.swing.JButton();
        LogoutIcon = new javax.swing.JButton();
        UpdateUserIcon = new javax.swing.JButton();
        ExitIcon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 1354, 10));

        AddUserIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddUserIcon.setForeground(new java.awt.Color(102, 255, 102));
        AddUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        AddUserIcon.setText("Add User");
        AddUserIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserIconActionPerformed(evt);
            }
        });
        getContentPane().add(AddUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 158, 300, -1));

        ProfileIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProfileIcon.setForeground(new java.awt.Color(102, 255, 102));
        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        ProfileIcon.setText("Profile");
        ProfileIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileIconActionPerformed(evt);
            }
        });
        getContentPane().add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 158, 300, -1));

        ViewUserIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewUserIcon.setForeground(new java.awt.Color(102, 255, 102));
        ViewUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewUser.png"))); // NOI18N
        ViewUserIcon.setText("View User");
        ViewUserIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewUserIconActionPerformed(evt);
            }
        });
        getContentPane().add(ViewUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 158, 300, -1));

        LogoutIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogoutIcon.setForeground(new java.awt.Color(102, 255, 102));
        LogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        LogoutIcon.setText("Log out");
        LogoutIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutIconActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 331, 300, -1));

        UpdateUserIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateUserIcon.setForeground(new java.awt.Color(102, 255, 102));
        UpdateUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateUser.png"))); // NOI18N
        UpdateUserIcon.setText("Update User");
        UpdateUserIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserIconActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 331, 300, -1));

        ExitIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExitIcon.setForeground(new java.awt.Color(102, 255, 102));
        ExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        ExitIcon.setText("Exit");
        ExitIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitIconActionPerformed(evt);
            }
        });
        getContentPane().add(ExitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 331, 300, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminDashboardBackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutIconActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_LogoutIconActionPerformed

    private void ExitIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitIconActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitIconActionPerformed

    private void AddUserIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserIconActionPerformed
        // TODO add your handling code here:
        new AddUser().setVisible(true);
    }//GEN-LAST:event_AddUserIconActionPerformed

    private void ViewUserIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewUserIconActionPerformed
        // TODO add your handling code here:
        new ViewUser().setVisible(true);
    }//GEN-LAST:event_ViewUserIconActionPerformed

    private void UpdateUserIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserIconActionPerformed
        // TODO add your handling code here:
        new UpdateUser().setVisible(true);
    }//GEN-LAST:event_UpdateUserIconActionPerformed

    private void ProfileIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileIconActionPerformed
        // TODO add your handling code here:
        new Profile(username).setVisible(true);
    }//GEN-LAST:event_ProfileIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserIcon;
    private javax.swing.JButton ExitIcon;
    private javax.swing.JButton LogoutIcon;
    private javax.swing.JButton ProfileIcon;
    private javax.swing.JButton UpdateUserIcon;
    private javax.swing.JButton ViewUserIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
