
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ibrah
 */
public class PharmacistDashboard extends javax.swing.JFrame {
    private String username = "";
    /**
     * Creates new form PharmacistDashboard
     */
    public PharmacistDashboard() {
        initComponents();
    }
    public PharmacistDashboard(String tempUsername) {
        initComponents();
        username = tempUsername;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SellMedicineIcon = new javax.swing.JButton();
        ViewMedicineIcon = new javax.swing.JButton();
        UpdateMedicineIcon = new javax.swing.JButton();
        LogoutIcon = new javax.swing.JButton();
        AddMedicineIcon = new javax.swing.JButton();
        ViewBillIcon = new javax.swing.JButton();
        ProfileIcon = new javax.swing.JButton();
        ExitIcon = new javax.swing.JButton();
        CloseIcon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 1366, 10));

        SellMedicineIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SellMedicineIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sellMedicine.png"))); // NOI18N
        SellMedicineIcon.setText("Sell Medicine");
        SellMedicineIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellMedicineIconActionPerformed(evt);
            }
        });
        getContentPane().add(SellMedicineIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 113, 400, -1));

        ViewMedicineIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewMedicineIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewUser.png"))); // NOI18N
        ViewMedicineIcon.setText("View Medicine");
        ViewMedicineIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMedicineIconActionPerformed(evt);
            }
        });
        getContentPane().add(ViewMedicineIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 255, 400, -1));

        UpdateMedicineIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateMedicineIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateUser.png"))); // NOI18N
        UpdateMedicineIcon.setText("Update Medicine");
        UpdateMedicineIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMedicineIconActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateMedicineIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 405, 400, -1));

        LogoutIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        LogoutIcon.setText("Logout");
        LogoutIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutIconActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 614, 400, -1));

        AddMedicineIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddMedicineIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addMedicine.png"))); // NOI18N
        AddMedicineIcon.setText("Add Medicine");
        AddMedicineIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMedicineIconActionPerformed(evt);
            }
        });
        getContentPane().add(AddMedicineIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 113, 400, -1));

        ViewBillIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewBillIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewBill.png"))); // NOI18N
        ViewBillIcon.setText("View Bill");
        ViewBillIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBillIconActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBillIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 255, 400, -1));

        ProfileIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        ProfileIcon.setText("Profile");
        ProfileIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileIconActionPerformed(evt);
            }
        });
        getContentPane().add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 405, 400, -1));

        ExitIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        ExitIcon.setText("Exit");
        ExitIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitIconActionPerformed(evt);
            }
        });
        getContentPane().add(ExitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 614, 400, -1));

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        CloseIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseIconActionPerformed(evt);
            }
        });
        getContentPane().add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminDashboardBackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseIconActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_CloseIconActionPerformed

    private void LogoutIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutIconActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_LogoutIconActionPerformed

    private void ExitIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitIconActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitIconActionPerformed

    private void ProfileIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileIconActionPerformed
        // TODO add your handling code here:
        new Profile(username).setVisible(true);
    }//GEN-LAST:event_ProfileIconActionPerformed

    private void AddMedicineIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMedicineIconActionPerformed
        // TODO add your handling code here:
        new AddMedicine().setVisible(true);
    }//GEN-LAST:event_AddMedicineIconActionPerformed

    private void ViewMedicineIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMedicineIconActionPerformed
        // TODO add your handling code here:
        new ViewMedicine().setVisible(true);
    }//GEN-LAST:event_ViewMedicineIconActionPerformed

    private void UpdateMedicineIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMedicineIconActionPerformed
        // TODO add your handling code here:
        new UpdateMedicine().setVisible(true);
    }//GEN-LAST:event_UpdateMedicineIconActionPerformed

    private void SellMedicineIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellMedicineIconActionPerformed
        // TODO add your handling code here:
        new SellMedicine(username).setVisible(true);
    }//GEN-LAST:event_SellMedicineIconActionPerformed

    private void ViewBillIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBillIconActionPerformed
        // TODO add your handling code here:
        new ViewBill().setVisible(true);
    }//GEN-LAST:event_ViewBillIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacistDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMedicineIcon;
    private javax.swing.JButton CloseIcon;
    private javax.swing.JButton ExitIcon;
    private javax.swing.JButton LogoutIcon;
    private javax.swing.JButton ProfileIcon;
    private javax.swing.JButton SellMedicineIcon;
    private javax.swing.JButton UpdateMedicineIcon;
    private javax.swing.JButton ViewBillIcon;
    private javax.swing.JButton ViewMedicineIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
