
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ibrah
 */
public class Profile extends javax.swing.JFrame {

    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String phoneNumberPattern = "^[0-9]*$";
    private String username = "";

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    public Profile(String tempUsername) {
        initComponents();
        username = tempUsername;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        UpdateIcon = new javax.swing.JButton();
        CloseIcon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PhoneNumberTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        WorkingTimeTxt = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Profile");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 850, 10));

        UpdateIcon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        UpdateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        UpdateIcon.setText("Update");
        UpdateIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateIconActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        CloseIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseIconActionPerformed(evt);
            }
        });
        getContentPane().add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 140));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        NameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 290, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        PhoneNumberTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(PhoneNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 290, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        EmailTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(EmailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 290, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        AddressTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(AddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 290, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Working Time");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        WorkingTimeTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(WorkingTimeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 290, -1));

        lblUsername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUsername.setText("Username");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseIconActionPerformed
        // TODO add your handling code here:
        setVisible(false);
//        int a = JOptionPane.showConfirmDialog(null, "Do you want to close application", "Select", JOptionPane.YES_NO_OPTION);
//        if (a == 0) {
//            System.exit(0);
//        }
    }//GEN-LAST:event_CloseIconActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/pharmacy_management_system_db";
        String user = "root";
        String dbpassword = "IBRAHIM2525";
        try{
            Connection con = DriverManager.getConnection(url, user, dbpassword);
            Statement st = con.createStatement();
            String sql = "SELECT * FROM STAFF WHERE username = '"+username+"'";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                NameTxt.setText(rs.getString("staff_name"));
                PhoneNumberTxt.setText(rs.getString("phone"));
                EmailTxt.setText(rs.getString("email"));
                AddressTxt.setText(rs.getString("address"));
                WorkingTimeTxt.setText(rs.getString("working_time"));
                lblUsername.setText(username);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown
    String url = "jdbc:mysql://localhost:3306/pharmacy_management_system_db";
        String user = "root";
        String dbpassword = "IBRAHIM2525";

    private void UpdateIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateIconActionPerformed
        // TODO add your handling code here:
        String name = NameTxt.getText();
        String phone = PhoneNumberTxt.getText();
        String email = EmailTxt.getText();
        String address = AddressTxt.getText();
        String working_time = WorkingTimeTxt.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Name field is required");
        }else if(phone.equals("")){
            JOptionPane.showMessageDialog(null, "Phone Number field is required");
        }else if(!phone.matches(phoneNumberPattern) || phone.length() != 10){
            JOptionPane.showMessageDialog(null, "Phone Number field is Invalid");
        }else if(email.equals("")){
            JOptionPane.showMessageDialog(null, "Email field is required");
        }else if(!email.matches(emailPattern)){
            JOptionPane.showMessageDialog(null, "Email field is Invalid");
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(null, "Address field is required");
        }else if(working_time.equals("")){
            JOptionPane.showMessageDialog(null, "Working Time field is required");
        }else{
            try{
                Connection con = DriverManager.getConnection(url, user, dbpassword);
                String sql = "UPDATE STAFF SET staff_name=?, phone=?, email=?, address=?, working_time=? WHERE username=? ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, name);
                pst.setString(2, phone);
                pst.setString(3, email);
                pst.setString(4, address);
                pst.setString(5, working_time);
                pst.setString(6, username);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Profile Successfully Updated");
                setVisible(false);
                new Profile(username).setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_UpdateIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JButton CloseIcon;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PhoneNumberTxt;
    private javax.swing.JButton UpdateIcon;
    private javax.swing.JTextField WorkingTimeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
