
import Common.OpenPdf;
import DAO.PharmacyUtils;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ibrah
 */
public class SellMedicine extends javax.swing.JFrame {

    public String numberPattern = "^[0-9]*$";
    private int finalTotalPrice = 0;
    private String billID = "";
    private String username = "";

    /**
     * Creates new form SellMedicine
     */
    public SellMedicine() {
        initComponents();
    }

    public SellMedicine(String tempUsername) {
        initComponents();
        username = tempUsername;
        setLocationRelativeTo(null);
    }
    
    String url = "jdbc:mysql://localhost:3306/pharmacy_management_system_db";
    String user = "root";
    String dbpassword = "IBRAHIM2525";
    private void medicineName(String nameOrMedicineID){
        DefaultTableModel model = (DefaultTableModel) MedicineTable.getModel();
        model.setRowCount(0);
        try{
            Connection con = DriverManager.getConnection(url, user, dbpassword);
            Statement st = con.createStatement();
            String sql = "SELECT * FROM MEDICINE WHERE medicine_name like '"+nameOrMedicineID+"%' or medicine_id like '"+nameOrMedicineID+"%'";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("medicine_id")+ "- "+ rs.getString("medicine_name")});
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void clearMedicineFields(){
        MedicineIDTxt.setText("");
        NameTxt.setText("");
        CompanyNameTxt.setText("");
        PricePerProductTxt.setText("");
        NoOfProductsTxt.setText("");
        TotalPriceTxt.setText("");
    }
    
    public String getMedicineID(String prefix){
        return prefix + System.nanoTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CloseIcon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SearchTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicineTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MedicineIDTxt = new javax.swing.JTextField();
        PricePerProductTxt = new javax.swing.JTextField();
        NameTxt = new javax.swing.JTextField();
        NoOfProductsTxt = new javax.swing.JTextField();
        CompanyNameTxt = new javax.swing.JTextField();
        TotalPriceTxt = new javax.swing.JTextField();
        AddToCartBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CartTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        PurchaseBtn = new javax.swing.JButton();
        lblTotalPrice = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminDashboardBackground.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sell Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 1366, 10));

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        CloseIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseIconActionPerformed(evt);
            }
        });
        getContentPane().add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, -1, -1));

        SearchTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTxtKeyReleased(evt);
            }
        });
        getContentPane().add(SearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 300, -1));

        MedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Medicine"
            }
        ));
        MedicineTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicineTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MedicineTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 300, 514));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Medicine ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price Per Product");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Company Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Products");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        MedicineIDTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(MedicineIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 300, -1));

        PricePerProductTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(PricePerProductTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 300, -1));

        NameTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 300, -1));

        NoOfProductsTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NoOfProductsTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NoOfProductsTxtKeyReleased(evt);
            }
        });
        getContentPane().add(NoOfProductsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 300, -1));

        CompanyNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(CompanyNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, -1));

        TotalPriceTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceTxtActionPerformed(evt);
            }
        });
        getContentPane().add(TotalPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 300, -1));

        AddToCartBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddToCartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        AddToCartBtn.setText("Add To Cart");
        AddToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddToCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        CartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Name", "Company Name", "Price Per Product", "No. of Products", "Total Price"
            }
        ));
        CartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CartTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 664, 250));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RWF");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, -1, -1));

        PurchaseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PurchaseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        PurchaseBtn.setText("Purchase & Print");
        PurchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PurchaseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 670, -1, -1));

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPrice.setText("00");
        getContentPane().add(lblTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminDashboardBackground.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1320, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseIconActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseIconActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void TotalPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceTxtActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        medicineName("");
        MedicineIDTxt.setEditable(false);
        NameTxt.setEditable(false);
        CompanyNameTxt.setEditable(false);
        PricePerProductTxt.setEditable(false);
        TotalPriceTxt.setEditable(false);
        
    }//GEN-LAST:event_formComponentShown

    private void SearchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTxtKeyReleased
        // TODO add your handling code here:
        String search = SearchTxt.getText();
        medicineName(search);
    }//GEN-LAST:event_SearchTxtKeyReleased

    private void MedicineTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicineTableMouseClicked
        // TODO add your handling code here:
        int index = MedicineTable.getSelectedRow();
        TableModel model = MedicineTable.getModel();
        String nameOrMedicineID = model.getValueAt(index, 0).toString();
        String medicineID[] = nameOrMedicineID.split("-", 0);
        try{
            Connection con = DriverManager.getConnection(url, user, dbpassword);
            Statement st = con.createStatement();
            String sql = "SELECT * FROM MEDICINE WHERE medicine_id = '"+medicineID[0]+"'";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                MedicineIDTxt.setText(medicineID[0]);
                NameTxt.setText(rs.getString("medicine_name"));
                CompanyNameTxt.setText(rs.getString("company"));
                PricePerProductTxt.setText(rs.getString("price"));
                NoOfProductsTxt.setText("");
                TotalPriceTxt.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_MedicineTableMouseClicked

    private void NoOfProductsTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoOfProductsTxtKeyReleased
        // TODO add your handling code here:
        String noOfProducts = NoOfProductsTxt.getText();
        if(!noOfProducts.equals("")){
            String price = PricePerProductTxt.getText();
            if(!noOfProducts.matches(numberPattern)){
                JOptionPane.showMessageDialog(this, "Number Of Products field is invalid");
            }
            int totalPrice = Integer.parseInt(noOfProducts) * Integer.parseInt(price);
            TotalPriceTxt.setText(String.valueOf(totalPrice));
        }
        else{
            TotalPriceTxt.setText("");
        }
    }//GEN-LAST:event_NoOfProductsTxtKeyReleased

    private void AddToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartBtnActionPerformed
        // TODO add your handling code here:
        String noOfProducts = NoOfProductsTxt.getText();
        String medicineID = MedicineIDTxt.getText();
        if(!noOfProducts.equals("") && !medicineID.equals("")){
            String name = NameTxt.getText();
            String companyName = CompanyNameTxt.getText();
            String pricePerProduct = PricePerProductTxt.getText();
            String totalPrice = TotalPriceTxt.getText();
            int checkStock = 0;
            int checkMedicineAlreadyExistInCart = 0;
            
            try{
                Connection con = DriverManager.getConnection(url, user, dbpassword);
                Statement st = con.createStatement();
                String sql = "SELECT * FROM MEDICINE WHERE medicine_id = '"+medicineID+"'";
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    if(rs.getInt("quantity") >= Integer.parseInt(noOfProducts)){
                        checkStock = 1;
                    }else{
                        JOptionPane.showMessageDialog(this, "Medicine is out of Stock. Only "+rs.getInt("quantity")+ " Left");
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
            if(checkStock == 1){
                DefaultTableModel dtm = (DefaultTableModel) CartTable.getModel();
                if(CartTable.getRowCount() != 0){
                    for(int i=0; i<CartTable.getRowCount(); i++){
                        if(Integer.parseInt(dtm.getValueAt(i, 0).toString()) == Integer.parseInt(medicineID)){
                            checkMedicineAlreadyExistInCart = 1;
                            JOptionPane.showMessageDialog(this, "This Medicine is Already in Cart");
                        }
                    }
                }
                if(checkMedicineAlreadyExistInCart == 0){
                    dtm.addRow(new Object[]{medicineID, name, companyName, pricePerProduct, noOfProducts, totalPrice});
                    finalTotalPrice = finalTotalPrice + Integer.parseInt(totalPrice);
                    lblTotalPrice.setText(String.valueOf(finalTotalPrice));
                    JOptionPane.showMessageDialog(this, "Added Successfully");
                }
                clearMedicineFields();
            }
                
              
        }else{
            JOptionPane.showMessageDialog(this, "Number Of Products & Medicine ID fields are required");
        }
    }//GEN-LAST:event_AddToCartBtnActionPerformed

    private void CartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartTableMouseClicked
        // TODO add your handling code here:
        int index = CartTable.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(this, "Do you want to romove this Medicine","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            TableModel model = CartTable.getModel();
            String total = model.getValueAt(index, 5).toString();
            finalTotalPrice = finalTotalPrice - Integer.parseInt(total);
            lblTotalPrice.setText(String.valueOf(finalTotalPrice));
            ((DefaultTableModel) CartTable.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_CartTableMouseClicked

    private void PurchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseBtnActionPerformed
        // TODO add your handling code here:
        if(finalTotalPrice != 0){
            billID = getMedicineID("Bill-");
            DefaultTableModel dtm = (DefaultTableModel) CartTable.getModel();
            if(CartTable.getRowCount() != 0){
                for(int i=0; i<CartTable.getRowCount(); i++){
                    try{
                        Connection con = DriverManager.getConnection(url, user, dbpassword);
                        Statement st = con.createStatement();
                        String update = "UPDATE MEDICINE SET quantity = quantity - "+Integer.parseInt(dtm.getValueAt(i, 4).toString()) +" WHERE medicine_id="+Integer.parseInt(dtm.getValueAt(i, 0).toString());
                        st.executeUpdate(update);
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this, e);
                    }
                }
            }
            try{
                SimpleDateFormat myFormat = new SimpleDateFormat("dd-MM-yyyy");
                Calendar cal = Calendar.getInstance();
                Connection con = DriverManager.getConnection(url, user, dbpassword);
                PreparedStatement pst = con.prepareStatement("INSERT INTO BILL (billID, billDate, totalPaid, generatedBy) VALUES (?,?,?,?)");
                pst.setString(1, billID);
                pst.setString(2, myFormat.format(cal.getTime()));
                pst.setInt(3, finalTotalPrice);
                pst.setString(4, username);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
            
            //Create Bill
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try{
                PdfWriter.getInstance(doc, new FileOutputStream(PharmacyUtils.billPath+""+billID+".pdf"));
                doc.open();
                Paragraph pharmacyName = new Paragraph("                              Pharmacy Management System\n");
                doc.add(pharmacyName);
                Paragraph starLine = new Paragraph("**************************************************");
                Paragraph details = new Paragraph("\tBill ID: "+billID+"\nDate: "+ new Date()+"\nTotal Paid: "+finalTotalPrice);
                doc.add(details);
                doc.add(starLine);
                PdfPTable tbl = new PdfPTable(6);
                tbl.addCell("Medicine ID");
                tbl.addCell("Name");
                tbl.addCell("Company Name");
                tbl.addCell("Price Per Product");
                tbl.addCell("No Of Products");
                tbl.addCell("Sub Total Price");
                for(int i=0; i<CartTable.getRowCount(); i++){
                    String a = CartTable.getValueAt(i, 0).toString();
                    String b = CartTable.getValueAt(i, 1).toString();
                    String c = CartTable.getValueAt(i, 2).toString();
                    String d = CartTable.getValueAt(i, 3).toString();
                    String e = CartTable.getValueAt(i, 4).toString();
                    String f = CartTable.getValueAt(i, 5).toString();
                    tbl.addCell(a);
                    tbl.addCell(b);
                    tbl.addCell(c);
                    tbl.addCell(d);
                    tbl.addCell(e);
                    tbl.addCell(f);
                }
                doc.add(tbl);
                doc.add(starLine);
                Paragraph thanksMsg = new Paragraph("Thank you for Shopping with Us");
                doc.add(thanksMsg);
                OpenPdf.openById(String .valueOf(billID));
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
            doc.close();
            setVisible(false);
            new SellMedicine(username).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Please add some Medicines to Cart");
        }
        
    }//GEN-LAST:event_PurchaseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartBtn;
    private javax.swing.JTable CartTable;
    private javax.swing.JButton CloseIcon;
    private javax.swing.JTextField CompanyNameTxt;
    private javax.swing.JTextField MedicineIDTxt;
    private javax.swing.JTable MedicineTable;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField NoOfProductsTxt;
    private javax.swing.JTextField PricePerProductTxt;
    private javax.swing.JButton PurchaseBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JTextField TotalPriceTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTotalPrice;
    // End of variables declaration//GEN-END:variables
}
