
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JFormattedTextField;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ibrah
 */
public class UpdateMedicine extends javax.swing.JFrame {
    public String numberPattern = "^[0-9]*$";
    /**
     * Creates new form UpdateMedicine
     */
    public UpdateMedicine() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CloseIcon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MedicineIDTxt = new javax.swing.JTextField();
        SearchIcon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        CompanyNameTxt = new javax.swing.JTextField();
        QuantityTxt = new javax.swing.JTextField();
        PriceTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AddQuantityTxt = new javax.swing.JTextField();
        UpdateIcon = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Update Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 10));

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        CloseIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseIconActionPerformed(evt);
            }
        });
        getContentPane().add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 93, -1, -1));

        MedicineIDTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(MedicineIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 90, 300, -1));

        SearchIcon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        SearchIcon.setText("Search");
        SearchIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconActionPerformed(evt);
            }
        });
        getContentPane().add(SearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 88, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 133, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 236, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 334, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Price Per Unite");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        NameTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 167, 300, -1));

        CompanyNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(CompanyNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 266, 300, -1));

        QuantityTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QuantityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTxtActionPerformed(evt);
            }
        });
        getContentPane().add(QuantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 362, 300, -1));

        PriceTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(PriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 300, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Add Quantity");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 405, -1, -1));

        AddQuantityTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(AddQuantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 402, 113, -1));

        UpdateIcon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        UpdateIcon.setText("Update");
        UpdateIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateIconActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseIconActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseIconActionPerformed

    private void QuantityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTxtActionPerformed

    String url = "jdbc:mysql://localhost:3306/pharmacy_management_system_db";
    String user = "root";
    String dbpassword = "IBRAHIM2525";
    private void SearchIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconActionPerformed
        // TODO add your handling code here:
        int checkMedicineExist = 0;
        String medicineID = MedicineIDTxt.getText();
        if(medicineID.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Medicine ID field is required");
        }else{
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
            try{
                Connection con = DriverManager.getConnection(url, user, dbpassword);
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM MEDICINE WHERE medicine_id = '"+medicineID+"'");
                while(rs.next()){
                    MedicineIDTxt.setEditable(false);
                    checkMedicineExist = 1;
                    NameTxt.setText(rs.getString("medicine_name"));
                    CompanyNameTxt.setText(rs.getString("company"));
                    QuantityTxt.setText(rs.getString("quantity"));
                    PriceTxt.setText(rs.getString("price"));
//                    ManufactureDate.setDate(rs.getDate("man_date"));
//                    ExpirationDate.setDate(rs.getDate("exp_date"));
                    QuantityTxt.setEditable(false);
                    String manDate = rs.getString("man_date");
                    String expDate = rs.getString("exp_date");
//                    Date expDate = ExpirationDate.getDate();
//                    Date ExpirationDate = rs.getDate("exp_date");
//                    String ManDate = "";
//                    String ExpDate = "";
//                    if(manDate !="" && expDate !=""){
//                        try{
//                            ManufactureDate.setDate(dFormat.parse(ManDate));
//                            ExpirationDate.setDate(dFormat.parse(ExpDate));
//                            ManDate = dFormat.format(ManufactureDate.getDate());
//                            Date manifactureDate = dFormat.parse(manDate);
////                            ManufactureDate.setDate(ManDate);
//                            ExpDate = dFormat.format(ExpirationDate.getDate());
//                            Date expirationDate = dFormat.parse(expDate);
////                            ExpirationDate.setDate(ExpDate).toString();
//                        }catch(Exception e){
//                            JOptionPane.showMessageDialog(this, e);
//                        }
//                    }
                    QuantityTxt.setEditable(false);
                    
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
            if(checkMedicineExist == 0){
                JOptionPane.showMessageDialog(this, "Medicine ID doesn't Exist");
            }
        }
    }//GEN-LAST:event_SearchIconActionPerformed

    private void UpdateIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateIconActionPerformed
        // TODO add your handling code here:
        String id = MedicineIDTxt.getText();
        String name = NameTxt.getText();
        String companyName = CompanyNameTxt.getText();
        String quantity = QuantityTxt.getText();
        String price = PriceTxt.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
//        Date manDate = ManufactureDate.getDate();
//        String manufactureDate = "";
//        if(manDate != null){
//            manufactureDate = dFormat.format(ManufactureDate.getDate());
//        }
//        Date ExpDate = ExpirationDate.getDate();
//        String expirationDate = "";
//        if(ExpDate != null){
//            expirationDate = dFormat.format(ExpirationDate.getDate());
//        }
        String addQuantity = AddQuantityTxt.getText();
        
        int totalQuantity = 0;
        if(addQuantity.equals("")){
            totalQuantity = Integer.parseInt(quantity);
        }else{
            totalQuantity = Integer.parseInt(quantity) + Integer.parseInt(addQuantity);
        }
        
       if(id.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Medicine ID field is Required");
        }else if(name.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Medicine Name field is Required");
        }else if(companyName.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Company Name field is Required");
//        }else if (manufactureDate.trim().equals("")) {
//            JOptionPane.showMessageDialog(this, "Manifacture Date field is required");
//        } else if (expirationDate.trim().equals("")) {
//            JOptionPane.showMessageDialog(this, "Expiration Date field is required");
        }else if(price.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Price field is Required");
        }else if(!price.matches(numberPattern)){
            JOptionPane.showMessageDialog(this, "Price field is Invalid");
        }else if(!addQuantity.matches(numberPattern)){
            JOptionPane.showMessageDialog(this, "Add Quantity field is Invalid");
        }else{
            try{
                Connection con = DriverManager.getConnection(url, user, dbpassword);
                String sql = "UPDATE MEDICINE SET medicine_name=?, company=?, quantity=?, price=? WHERE medicine_id=? ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, name);
                pst.setString(2, companyName);
//                pst.setString(3, manufactureDate);
//                pst.setString(4, expirationDate);
                pst.setInt(3, totalQuantity);
                pst.setString(4, price);
                pst.setString(5, id);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Medicine Successfully Updated");
                setVisible(false);
                new UpdateMedicine().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
//            if(totalQuantity == 0){
//                
//            }
        }
    }//GEN-LAST:event_UpdateIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddQuantityTxt;
    private javax.swing.JButton CloseIcon;
    private javax.swing.JTextField CompanyNameTxt;
    private javax.swing.JTextField MedicineIDTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JTextField QuantityTxt;
    private javax.swing.JButton SearchIcon;
    private javax.swing.JButton UpdateIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
