
import DAO.StaffDAO;
import Model.StaffModel;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ibrah
 */
public class UpdateUser extends javax.swing.JFrame {
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String phoneNumberPattern = "^[0-9]*$";
    /**
     * Creates new form UpdateUser
     */
    public UpdateUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CloseIcon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        StaffRoleCombo = new javax.swing.JComboBox<>();
        NameTxt = new javax.swing.JTextField();
        PhoneNumberTxt = new javax.swing.JTextField();
        SearchTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        WorkingTimeTxt = new javax.swing.JTextField();
        SearchIcon = new javax.swing.JButton();
        UpdateIcon = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Update User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 10));

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        CloseIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseIconActionPerformed(evt);
            }
        });
        getContentPane().add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Staff Role");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Working Time");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Username");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        StaffRoleCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StaffRoleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist" }));
        StaffRoleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffRoleComboActionPerformed(evt);
            }
        });
        getContentPane().add(StaffRoleCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 330, -1));

        NameTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 330, -1));

        PhoneNumberTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PhoneNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTxtActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 330, -1));

        SearchTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtActionPerformed(evt);
            }
        });
        getContentPane().add(SearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 280, -1));

        EmailTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(EmailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 350, -1));

        AddressTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTxtActionPerformed(evt);
            }
        });
        getContentPane().add(AddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 350, -1));

        WorkingTimeTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(WorkingTimeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 350, -1));

        SearchIcon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        SearchIcon.setText("Search");
        SearchIcon.setActionCommand("");
        SearchIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconActionPerformed(evt);
            }
        });
        getContentPane().add(SearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        UpdateIcon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        UpdateIcon.setText("Update");
        UpdateIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateIconActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StaffRoleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffRoleComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffRoleComboActionPerformed

    private void PhoneNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTxtActionPerformed

    private void AddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTxtActionPerformed

    private void CloseIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseIconActionPerformed
        // TODO add your handling code here:
        setVisible(false);
//        int a = JOptionPane.showConfirmDialog(null, "Do you want to close application", "Select", JOptionPane.YES_NO_OPTION);
//        if (a == 0) {
//            System.exit(0);
//        }
    }//GEN-LAST:event_CloseIconActionPerformed
    String url = "jdbc:mysql://localhost:3306/pharmacy_management_system_db";
    String user = "root";
    String dbpassword = "IBRAHIM2525";
    private void SearchIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconActionPerformed
        // TODO add your handling code here:
        int checkUserExist = 0;
        String Username = SearchTxt.getText();
        if(SearchTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username to Search is Required!");
        }else{
            try{
//            StaffDAO dao = new StaffDAO();
//            StaffModel stObj = new StaffModel();
//            stObj.setUsername(SearchTxt.getText());
//            StaffModel theStaff = dao.findStaffById(stObj);
            Connection con = DriverManager.getConnection(url, user, dbpassword);
            Statement st = con.createStatement();
            String sql = "SELECT * FROM STAFF WHERE username = '"+Username+"'";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                StaffRoleCombo.setSelectedItem(rs.getString("staffRole"));
                NameTxt.setText(rs.getString("staff_name"));
                PhoneNumberTxt.setText(rs.getString("phone"));
                EmailTxt.setText(rs.getString("email"));
                AddressTxt.setText(rs.getString("address"));
                WorkingTimeTxt.setText(rs.getString("working_time"));
                checkUserExist = 1;
            
            }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex);
            }
            if(checkUserExist == 0){
                JOptionPane.showMessageDialog(this, "Staff with that Username doesn't exist!");
            }
        }    
        
    }//GEN-LAST:event_SearchIconActionPerformed

    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxtActionPerformed

    private void UpdateIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateIconActionPerformed
        // TODO add your handling code here:
        
        
        String name = NameTxt.getText();
        String phone = PhoneNumberTxt.getText();
        String email = EmailTxt.getText();
        String address = AddressTxt.getText();
        String working_time = WorkingTimeTxt.getText();
        String username = SearchTxt.getText();
        String role = (String) StaffRoleCombo.getSelectedItem();
        
        if(role.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Staff Role field is Required");
        }else if(name.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Staff Name field is Required");
        }else if(phone.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Phone Number field is Required");
        }else if(!phone.matches(phoneNumberPattern)){
            JOptionPane.showMessageDialog(this, "Phone Number field is Invalid");
        }else if(email.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Email field is Required");
        }else if(!email.matches(emailPattern)){
            JOptionPane.showMessageDialog(this, "Email field is Invalid");
        }else if(address.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Address field is Required");
        }else if(working_time.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Working Time field is Required");
        }else{
            try{
                Connection con = DriverManager.getConnection(url, user, dbpassword);
                String sql = "UPDATE STAFF SET staff_name=?, phone=?, email=?, address=?, working_time=?, staffRole=? WHERE username=? ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, name);
                pst.setString(2, phone);
                pst.setString(3, email);
                pst.setString(4, address);
                pst.setString(5, working_time);
                pst.setString(6, role);
                pst.setString(7, username);
                pst.executeUpdate();
                
                String selectRoleSql = "SELECT staffRole FROM STAFF WHERE username=?";
                PreparedStatement selectRolePst = con.prepareStatement(selectRoleSql);
                selectRolePst.setString(1, username);
                ResultSet rs = selectRolePst.executeQuery();

                if (rs.next()) {
                    String staffRole = rs.getString("staffRole");
                    // Update the StaffRoleCombo based on the retrieved staffRole
                    if (rs.getString("StaffRole").equals("Admin")) {
                        StaffRoleCombo.removeAllItems();
                        StaffRoleCombo.addItem("Admin");
                        StaffRoleCombo.addItem("Pharmacist");
                    } else {
                        StaffRoleCombo.removeAllItems();
                        StaffRoleCombo.addItem("Pharmacist");
                        StaffRoleCombo.addItem("Admin");
                    }
                }

                JOptionPane.showMessageDialog(this, "User Successfully Updated");
                setVisible(false);
                new UpdateUser().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_UpdateIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JButton CloseIcon;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PhoneNumberTxt;
    private javax.swing.JButton SearchIcon;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JComboBox<String> StaffRoleCombo;
    private javax.swing.JButton UpdateIcon;
    private javax.swing.JTextField WorkingTimeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
