
import DAO.StaffDAO;
import Model.StaffModel;
//import com.sun.jdi.connect.spi.Connection;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ibrah
 */
public class ViewUser extends javax.swing.JFrame {
    DefaultTableModel tableModel = new DefaultTableModel();
    private String username = "";
    /**
     * Creates new form ViewUser
     */
    public ViewUser() {
        initComponents();
        addColumnHeaderName();
        addRowDataToTable();
    }
    
    public ViewUser(String tempUsername) {
        initComponents();
        
        username = tempUsername;
        setLocationRelativeTo(null);
    }
    
    private void addColumnHeaderName(){
        tableModel.addColumn("Staff ID");
        tableModel.addColumn("Staff Role");
        tableModel.addColumn("Staff Names");
        tableModel.addColumn("Username");
        tableModel.addColumn("Password");
        tableModel.addColumn("Phone Number");
        tableModel.addColumn("Email");
        tableModel.addColumn("Address");
        tableModel.addColumn("Working Time");
        ViewUserTable.setModel(tableModel);
    }
    
    private void addRowDataToTable(){
        tableModel.setRowCount(0);
        StaffDAO dao = new StaffDAO();
        List<StaffModel> staffList = dao.retrieveAllStaff();
        for(StaffModel theStaff :  staffList){
            tableModel.addRow(new Object[]{
                theStaff.getStaff_id(),
                theStaff.getStaffRole(),
                theStaff.getStaff_name(),
                theStaff.getUsername(),
                theStaff.getPassword(),
                theStaff.getPhone(),
                theStaff.getEmail(),
                theStaff.getAddress(),
                theStaff.getWorking_time()
                                
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CloseIcon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewUserTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("View User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 6, -1, -1));

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        CloseIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseIconActionPerformed(evt);
            }
        });
        getContentPane().add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 10));

        ViewUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ViewUserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewUserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ViewUserTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 823, 313));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Click on row to delete User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 443, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseIconActionPerformed
        // TODO add your handling code here:
        setVisible(false);
//        int a = JOptionPane.showConfirmDialog(null, "Do you want to close application", "Select", JOptionPane.YES_NO_OPTION);
//        if (a == 0) {
//            System.exit(0);
//        }
    }//GEN-LAST:event_CloseIconActionPerformed
    String url = "jdbc:mysql://localhost:3306/pharmacy_management_system_db";
    String user = "root";
    String dbpassword = "IBRAHIM2525";
    private void ViewUserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewUserTableMouseClicked
        // TODO add your handling code here:
//        StaffDAO dao = new StaffDAO();
//        List<StaffModel> staffList = dao.retrieveAllStaff();
//        StaffModel theStaff = new StaffModel();
        int index = ViewUserTable.getSelectedRow();
        TableModel model = ViewUserTable.getModel();
        String id = model.getValueAt(index, 0).toString();
        String usernameTable = model.getValueAt(index, 3).toString();
//        if(theStaff.getUsername().equals(usernameTable)){
        if(username.equals(usernameTable)){
            JOptionPane.showMessageDialog(this, "You cannot Delete your own account");
        }else{
            int a = JOptionPane.showConfirmDialog(this, "Do you want to Delete this account","Select",JOptionPane.YES_NO_OPTION);
            if(a == 0){
                try{
                    Connection con = (Connection) DriverManager.getConnection(url, user, dbpassword);
                    String sql = "DELETE FROM STAFF where staff_id=?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, id);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Staff Successfully Deleted");
                    setVisible(false);
//                    new ViewUser(username).setVisible(true);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, e);
                }
        
            }
        }
    }//GEN-LAST:event_ViewUserTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseIcon;
    private javax.swing.JTable ViewUserTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
